### ISSUE TITLE
`OPENBLAS_XXX` cross compile options aren't respected under linux

### ISSUE THREAD

**Issue by mlaventure** [blas-lapack-rs/openblas-src#101]
While trying to cross-compile as a dependency of a project under the Yocto Project environment, I was surprised to realize that the `OPENBLAS_CC` and friends are not used when building for `linux`. 

Is this intended? The README clearly states that those are meant to be used for cross-compiling. Should openbas-build be updated to respect those variables?

**Comment by ivan-aksamentov** [comment]
The system with cherry-picked renamed env vars is needlessly complex, broken and cannot keep up with upstream updates. Env vars should be passed as is. Half of the code in these crates can be removed.
