### ISSUE TITLE
Unnecessary cross-compilation for openblas-build

### ISSUE THREAD

**Issue by gkobeaga** [blas-lapack-rs/openblas-src#115]
In the process of cross-compiling, `openblas-build` is compiled to both host and target architectures, see #114. Building to the target architectures might not be necessary since `openblas-build` has its utilization exclusively for the download/build sequence of `OpenBLAS`.

As per my understanding, this happens because: 1) `openblas-build`  is a `build-dependency` for `openblas-src`,  so it is compiled to the host architecture; 2) it's a member of the virtual workspace, and it also ends up getting compiled to the target architecture.

One potential solution could be to remove `openblas-build` from the workspace. Stripping it away would result in a virtual workspace containing a single crate. Consequently, the logical step would be to move `openblas-src` to the root.

**Comment by Dirreke** [comment]
It may be because you don't set the `--package` or `manifest-path` to `openblas-src`. Feel free to open it again
