### ISSUE TITLE
New maintainers to openblas-src

### ISSUE THREAD

**Issue by Dirreke** [blas-lapack-rs/openblas-src#122]
Hi, is there any new maintainer could be added to this repository or at least get the next release out as  a transition thing similar to `ndarray-linalg`?
@termoshtt @bluss

**Comment by IvanUkhov** [comment]
Hello, it has been mainly Toshiki who has been taking care of this crate during the last years. I suppose he does not have as much time anymore. It would then indeed make sense if add as maintainers more people who are knowledgeable in this area. Do you have anybody specific in mind?

**Comment by Dirreke** [comment]
If you need, I'd love to temporarily take over the work. I’m familiar with these math libraries and cross-compilation. However, I can’t guarantee the time I’ll be able to dedicate, so my options are to keep the crate up-to-date, address major bugs, and, if feasible, implement new features.

**Comment by IvanUkhov** [comment]
Sounds good. I have added you to the Sources team, which covers all `-src` crates.
