### ISSUE TITLE
Move to a dedicated organization

### ISSUE THREAD

**Issue by IvanUkhov** [blas-lapack-rs/openblas-src#21]
@cmr, what do you think about collecting and maintaining all BLAS- and LAPACK-related crates under a separate organization dedicated to this particular purpose?

I’ve already created an organization called [BLAS and LAPACK for Rust](https://github.com/blas-lapack-rs) and moved all relevant crates from Stainless Steel to that organization. @astraw has also moved `accelerate-src` there.

Thanks!

**Comment by IvanUkhov** [comment]
Hi @cmr, sorry for bothering. Have you given any thought to this?

**Comment by cmr** [comment]
can’t believe I forgot to do this for so long. done!

**Comment by IvanUkhov** [comment]
Thank you! Can you also please move `netlib-src`?

**Comment by cmr** [comment]
on it :)
