### ISSUE TITLE
Problems with GNU toolchain on Windows

### ISSUE THREAD

**Issue by IvanUkhov** [blas-lapack-rs/openblas-src#22]
See [blas/#27](https://github.com/blas-lapack-rs/blas/issues/27).

**Comment by stiv-yakovenko** [comment]
HI! So is it possible to make this stuff build itself automatically with gnu toolchain?

**Comment by mattico** [comment]
What can be improved:
1. Add a windows guide to the readme [like my comment](https://github.com/blas-lapack-rs/blas/issues/27#issuecomment-346915404).
2. Use pkg-config in the build script to find libraries, so that step 7. isn't necessary.

I can submit a PR for these.

**Comment by IvanUkhov** [comment]
Regarding guidelines, I’ve created a [Wiki page](https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki/Usage-on-Windows) for this. Everybody is welcome to contribute.

Regarding `pkg-config`, it was [not possible](https://github.com/xianyi/OpenBLAS/issues/598) previously. Not sure how it’s not, but it’s the way to go.

Thanks!

**Comment by mattico** [comment]
pkg-config does work to find libopenblas for me, but it doesn't work for libgfortran, and there isn't a .pc file for it. A motivated person could try to get one into upstream (MSYS2 and/or gfortran).

**Comment by stiv-yakovenko** [comment]
Excuse me for not being familiar with rust dependency/build system. But isn't it possible simply to copy all prebuilt win32/64 openblas dependencies with the package, since we know what compiler will be used?

**Comment by IvanUkhov** [comment]
I close this due to the recent development.
