### ISSUE TITLE
GEMM returning zeroes on macos with static linking

### ISSUE THREAD

**Issue by kali** [blas-lapack-rs/openblas-src#24]
Hey, I noticed then the GEMM functions were not working on macOS with static linking. I have extended travis configuration to build more combinaisons, and added a GEMM testcase here.

https://github.com/snipsco/openblas-src/tree/1db4cfce5e671fedba9b19f8e156bd9dbb7cdaf9

Travis picks the error here:

https://travis-ci.org/snipsco/openblas-src/builds/355009003

But I am not too sure how to debug that... No problem with static on linux, no problem with dyn on mac...

**Comment by IvanUkhov** [comment]
Perhaps, this should be reported in OpenBLAS, if still relevant.
