### ISSUE TITLE
The static feature doesn't static link to the in-tree openblas on Debian Bullseye when libopenblas-dev is installed

### ISSUE THREAD

**Issue by maoe** [blas-lapack-rs/openblas-src#60]
The static feature is (I think) supposed to build the openblas source in the submodule and link it statically but it appears that on Debian Bullseye it links to the system library (libopenblas-dev) instead. On Ubuntu Bionic it seems to work fine.

Steps to reproduce:

1. checkout my repro branch:
```
git clone https://github.com/maoe/openblas-src.git
cd openblas-src
git checkout print-config
```
2. build docker images
```
docker build -f Dockerfile.debian-bullseye -t openblas-src-bullseye .
docker build -f Dockerfile.ubuntu-bionic -t openblas-src-bionic .
```
3. run the containers
```
% docker run -it --rm openblas-src-bullseye
OpenBLAS 0.3.13 NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
% docker run -it --rm openblas-src-bionic   
NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell
```

FWIW OpenBLAS 0.3.13 is installed via apt-get install in both containers.

**Comment by maoe** [comment]
Apparently Ubuntu Focal has the same issue:

```
% docker build -f Dockerfile.ubuntu-focal -t openblas-src-focal .
% docker run -it --rm openblas-src-focal                         
OpenBLAS 0.3.8 NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge MAX_THREADS=64
```

**Comment by IvanUkhov** [comment]
Thank you for the issue! This block should probably be updated:

https://github.com/blas-lapack-rs/openblas-src/blob/9d074eb54f3155e3fe00c98aece116f811fdbc5f/openblas-src/build.rs#L66

We do not seem to be doing anything for Linux.

**Comment by termoshtt** [comment]
Thanks a lot!
