### ISSUE TITLE
Stop the failing AppVeyor integration

### ISSUE THREAD

**Issue by maoe** [blas-lapack-rs/openblas-src#66]
Looks like it's [broken](https://ci.appveyor.com/project/IvanUkhov/openblas-src/builds/37524058) and there are a few Windows jobs on [GitHub Actions](https://github.com/blas-lapack-rs/openblas-src/runs/1796476742). I feel a bit uncomfortable to see the red cross marks on every commit and PR. Could we stop the AppVeyor integration?

**Comment by IvanUkhov** [comment]
@termoshtt, do you know the reason for this failing integration? I am not that familiar with how things are on Windows:

https://github.com/blas-lapack-rs/openblas-src/blob/master/.github/workflows/openblas-src.yml#L10

**Comment by termoshtt** [comment]
CI by AppVeyer has been already replaced by GitHub Actions's windows target. What we have to do is to turn off the AppVeyer integration, but I do not have its enough authority on AppVeyer.

**Comment by IvanUkhov** [comment]
Aha, thank you for explaining! Never worked with GitHub Actions and imagined the architecture differently. But it makes more sense now. Disabled!
