### ISSUE TITLE
Set custom TARGET (linux)

### ISSUE THREAD

**Issue by cassiersg** [blas-lapack-rs/openblas-src#70]
The `openblas-build` crate offers an interface to select the `TARGET` make variable, however the `openblas-src` crate offers no way to set this option. Furthermore, the `openblas-build` crate clears the `TARGET` environment variable before calling make, leaving no way to set the `TARGET` of the openblas build.

What is the best way of solving this ?

In general, what is the supported way to customize the OpenBLAS build ? Environment variables seem to work fine, except for TARGET.

**Comment by M1cha** [comment]
for me, `OPENBLAS_TARGET` works just fine.
