### ISSUE TITLE
Disable OpenBLAS threading by default

### ISSUE THREAD

**Issue by jturner314** [blas-lapack-rs/openblas-src#73]
Rust code assumes that threads can be used without restriction. So, by default, we should disable OpenBLAS threading and enable locking with `USE_THREAD=0 USE_LOCKING=1`, since [the docs indicate that threading by the application conflicts with threading by OpenBLAS.](https://github.com/xianyi/OpenBLAS/wiki/Faq#multi-threaded) We can allow the user to enable OpenBLAS threading if desired with an environment variable. (An environment variable is more appropriate than a feature flag, because only the user building the final binary has enough information to know whether enabling OpenBLAS threading is safe for their application.)

**Comment by danieldk** [comment]
I just wanted to mention that we have run into this issue several times, both when using openblas-src, but also when using OpenBLAS with threaded applications outside the Rust ecosystem. The only way to reliably use OpenBLAS reliably in threaded applications is to build it with `USE_THREAD=0 USE_LOCKING=1` as @jturner314 suggests, or enabling threading and locking and using one of the environment variables mentioned in the linked FAQ entry (e.g. `OPENBLAS_NUM_THREADS=1`).

**Comment by IvanUkhov** [comment]
Thank you for the feedback. We have to decide what to make the default. It feels like we want it to be disabled by default to provide as much safety as possible. For experienced users, there will be a feature to enable.

**Comment by Dirreke** [comment]
Hi everyone, the OpenBLAS makefile now sets use_locking=1 if we don’t specify use_thread or use_openmp. The feature use_thread in openblas-src is disabled by default. Therefore, I believe we can close this issue. However, feel free to reopen it if you have any concerns.
