### ISSUE TITLE
Link against libgfortran statically when static feature is enabled

### ISSUE THREAD

**Issue by emmatyping** [blas-lapack-rs/openblas-src#74]
I use openblas for a Python package, so I statically link most of the C dependencies I have. However, when I activate the static feature it failed the manylinux check because it is dynamically linking to libgfortran.so.5

This seems to happen when the lapacke feature is activated, but not otherwise.

**Comment by IvanUkhov** [comment]
If you need OpenBLAS for a Python package, how does Rust appear in the picture?

**Comment by ethanhs** [comment]
I'm using ndarray and rust-numpy

**Comment by Dirreke** [comment]
Duplicate #88
