### ISSUE TITLE
Syntax error near unexpected token

### ISSUE THREAD

**Issue by gilcu2** [blas-lapack-rs/openblas-src#75]
Hi, I am trying to build a package that depend on  openblas-src on an Archlinux i7-1165G7.
It builds it with: features = ["cblas", "static"]
When building I get:

/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `ar  -ru ../libopenblas_(null)p-r0.3.14.a

I check the Makefile.conf generated and it has LIBCORE=(null)
What can I do?

**Comment by IvanUkhov** [comment]
Please try to compile OpenBLAS manually (by cloning the OpenBLAS repository and following the corresponding instructions)
 to confirm that this is a problem with the original build system. If you get the same error, I’d recommend opening an issue in the OpenBLAS repository instead.

**Comment by gilcu2** [comment]
Fixed by OpenBlas, thanks

**Comment by gilcu2** [comment]
Fixed by OpenBlas

**Comment by gilcu2** [comment]
They fixed the problem in develop branch but when I try to build another package that depends on openblas-src the problem follows. Do you need to do something to catch the updated version?

**Comment by IvanUkhov** [comment]
Yes, one would have to update the submodule in this folder:

https://github.com/blas-lapack-rs/openblas-src/tree/master/openblas-src

Once it is released, please feel free to open a pull request.
