### ISSUE TITLE
[Help needed] Make a release

### ISSUE THREAD

**Issue by Ykid** [blas-lapack-rs/openblas-src#84]
Hi,

Thank you for writing this repo. I am using an M1 Mac for development in rust but I am running into compilation issues.
https://github.com/xianyi/OpenBLAS/issues/3222

It seems the above issue is addressed in 0.3.16 where existing codebase was already using 0.3.17 but the main branch is not released to crates.io so I cannot pull the latest version. Wondering if any of you can help update the release?

Thanks!

**Comment by termoshtt** [comment]
https://github.com/blas-lapack-rs/openblas-src/releases/tag/openblas-src-v0.10.5 done
